apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dms-misura-service-build
  namespace: 1499-ci-cd
spec:
  failedBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: dms-misura-service:latest
  postCommit: {}
  resources:
    limits:
      cpu: 250m
      memory: 200Mi
  runPolicy: Serial
  source:
    dockerfile: "FROM redhat-openjdk-18/openjdk18-openshift\r\nCOPY *.jar app.jar\r\nEXPOSE 8090\r\nCMD
      [\"java\", \"-Djava.security.egd=file:/dev/./urandom\", \"-jar\", \"app.jar\",
      \"--jwt.secret=${JWT_SECRET}\", \"--jwt.profiler-url=${JWT_PROFILER_URL}\",
      \"--jwt.enabled=${JWT_ENABLED}\", \"--jwt.public-key=${PUBLIC_KEY_TOKEN}\", 
      \"--logging.level.it.eng.snam.summer.dmsmisuraservice.security=${LOGGING_LEVEL_SECURITY}\",
      \"--logging.level.it.eng.snam.summer.dmsmisuraservice.controller=${LOGGING_LEVEL_CONTROLLER}\",
      \"--logging.level.it.eng.snam.summer.dmsmisuraservice.service=${LOGGING_LEVEL_SERVICE}\",
      \"--logging.level.root=${LOGGING_LEVEL_ROOT}\"]"
    type: Dockerfile
  strategy:
    dockerStrategy:
      noCache: true
    type: Docker
  successfulBuildsHistoryLimit: 2
  triggers: []
